export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const FETCH_MESSAGE ='FETCH_MESSAGE'
export const MARK_ALL_MESSAGES ='MARK_ALL_MESSAGES'
export const REQUEST_PROFILE ='REQUEST_PROFILE'
export const RECEIVE_PROFILE ='RECEIVE_PROFILE'
export const GET_COLLECTED_TOPICS ='GET_COLLECTED_TOPICS'
export const REQUEST_TOPICS ='REQUEST_TOPICS'
export const RECEIVE_TOPICS ='RECEIVE_TOPICS'
export const SELECT_TAB ='SELECT_TAB'
export const RECORD_SCROLLT = 'RECORD_SCROLLT'
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE'
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE'
export const CHANGE_CURRENT_TOPICID = 'CHANGE_CURRENT_TOPICID'
export const RECORD_ARICILCE_SCROLLT = 'RECORD_ARICILCE_SCROLLT'
export const SWITCH_SUPPORT = 'SWITCH_SUPPORT'
export const FETCH_COMMENT = 'FETCH_COMMENT'




